[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
governance = "pytGY6tWRgGinSCvRLnSv4fHfBTMoiDGiCsesmHWM6U"
integrity_pool = "5ukY1VB5gm1mynieWvcy92amcaVPKMSYawN5L96meh7t"
profile = "bR3uQJLEmg2H46GuozXn8uNQmp2DaZEp6EK1kW56npd"
publisher_caps = "FaEDHKZKMDemCskgseX4A4r4AxiPCR5cha9vNzd6JUzY"
staking = "7VgwUAtQbEyd2Ssa9ajMyUJFpbdxNYAKsmkECtZbw3pp"
wallet_tester = "321KojcMTHwEwzDjt9j71iowtqMPMrfvQ6at1xbJdJWS"

[programs.localnet]
chat = "gCHAtYKrUUktTVzE4hEnZdLV4LXrdBf6Hh9qMaJALET"
governance = "pytGY6tWRgGinSCvRLnSv4fHfBTMoiDGiCsesmHWM6U"
integrity_pool = "5ukY1VB5gm1mynieWvcy92amcaVPKMSYawN5L96meh7t"
profile = "bR3uQJLEmg2H46GuozXn8uNQmp2DaZEp6EK1kW56npd"
publisher_caps = "FaEDHKZKMDemCskgseX4A4r4AxiPCR5cha9vNzd6JUzY"
staking = "7VgwUAtQbEyd2Ssa9ajMyUJFpbdxNYAKsmkECtZbw3pp"
wallet_tester = "321KojcMTHwEwzDjt9j71iowtqMPMrfvQ6at1xbJdJWS"

[programs.mainnet]
governance = "pytGY6tWRgGinSCvRLnSv4fHfBTMoiDGiCsesmHWM6U"
integrity_pool = "5ukY1VB5gm1mynieWvcy92amcaVPKMSYawN5L96meh7t"
profile = "bR3uQJLEmg2H46GuozXn8uNQmp2DaZEp6EK1kW56npd"
publisher_caps = "FaEDHKZKMDemCskgseX4A4r4AxiPCR5cha9vNzd6JUzY"
staking = "7VgwUAtQbEyd2Ssa9ajMyUJFpbdxNYAKsmkECtZbw3pp"
wallet_tester = "321KojcMTHwEwzDjt9j71iowtqMPMrfvQ6at1xbJdJWS"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "./app/keypairs/localnet_authority.json"

[workspace]
members = ["programs/staking", "programs/wallet-tester", "programs/profile", "programs/integrity-pool", "programs/publisher-caps"]

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/staking.ts"

[validator]
ledger_dir = "./.anchor/test-ledger"

[path]
idl_path = "./target/idl/staking.json"
binary_path = "./target/deploy/staking.so"
governance_path = "./tests/programs/governance.so" # This is the version of governance with the extra instructions for testing, check PR 184 for more info
chat_path = "./tests/programs/chat.so"
wallet_tester_path = "./target/deploy/wallet_tester.so"
profile_path = "./target/deploy/profile.so"
integrity_pool_path = "./target/deploy/integrity_pool.so"
